language: node_js

node_js:
  - stable

services:
  - mongodb

before_install: cd sporter-api

install:
  - npm i
  - npm i -g codecov

script: npm test

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha ./src/**/*.test.js --report lcovonly -- -R spec
  - codecov