FORMAT: 1A
HOST: http://sporter.com/api

# Sporter API

This is the REST API used internally by the Sporter App. This API blueprint is subject to change due to
technology restrictions, performance optimizations or changing requirements.

## Authentication [/sessions]

## Authenticate [POST]

+ Request (application/json)
            
    + Attributes
    
        + email: user@test.com (string, required)
        + password: userpass (string, required)
    
+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + data
            + token: <token> (string, required)
        
## Users Collection [/users]

### Register a New User [POST]

+ Request (application/json)

    + Attributes
        
        + email: user@test.com (string, required)
        + password: userpass (string, required)
        + firstName: User (string, required)
        + lastName: Test (string, required)
        + age: 30 (string, required)
        + location: Madrid, Spain (string, required)

+ Response 200 (application/json; charset=utf-8)

    + Body

    + Attributes
        
        + data
            + token: <token> (required, string)
            
## User [/users/{id}]

### Get User Information [GET]

+ Parameters
    
    + id: 58fab28f0826df9d2f09bd6f (string, required)

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + data
            + user
            
                + id: 58fab28f0826df9d2f09bd6f
                + email: user@test.com
                + updatedAt: `2017-04-24T15:58:53.598Z`
                + createdAt: `2017-04-24T15:58:53.598Z`
                + firstName: User
                + lastName: Test
                + age: 30
                + location: `Madrid, Spain`
                
### Update User Information [PUT]

+ Parameters

    + id: 58fab28f0826df9d2f09bd6f (string, required)
    
+ Request (application/json)
    
    + Header
    
            Authorization: Bearer <token>
    
    + Attributes
        
        + email: newuser@test.com (string, required)
        + password: newuserpass (string, required)
        + firstName: User (string, required)
        + lastName: Test (string, required)
        + age: 30 (string, required)
        + location: Barcelona, Spain (string, required)
        
+ Response 204 (application/json; charset=utf-8)
 

### Delete a User [DELETE]

+ Parameters

    + id: 58fab28f0826df9d2f09bd6f (string, required)

+ Request
    
    + Header
    
            Authorization: Bearer <token>

+ Response 204 (application/json; charset=utf-8)